name: Validate Data

on:
  push:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install containerlab
        run: |
          bash -c "$(curl -sL https://get-clab.srlinux.dev)" -- -v 0.14.3
